title:            Suntong's blog
description:      I Was Growing Fast.
logo:             logo.png
disqus_shortname: shortname
# 为站点的页眉和页脚分配一个默认图像。
default_bg:       default_bg.jpg
search:           true
share:            false
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
# 读取时间是一个计算器，提供基于字数的后读取时间。 建议使用。
readtime:         false
# Turn on or off the fin animations in the header and footer
# 在页眉和页脚上打开或关闭fin动画。
triangleheader:	  true
animated_fins:    true
# Specify the fin color in RGB value 在RGB值中指定fin颜色。
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
# 将url更改为您的域。在本地工作时，离开localhost服务器或空白。
url:          http://suntong.me       
# Gems used
gems:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag

# Archives configuration
# https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    # year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

# Owner/author information
author: Sun tong
  name:           Sun tong
  picture:        Suntong.jpg
  email:          jsonsuntong@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Every day is a new beginning.
  # Social networking links used in footer. Update and remove as you like.
  github: JsonSun
# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags

# Sitemap configuration
# https://github.com/kinnetica/jekyll-plugins
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
markdown:    kramdown
highlighter: rouge
paginate:    8
paginate_path: "/blog/:num/"

# https://github.com/mojombo/jekyll/wiki/Permalinks
collections:
  posts:
    output: true
    permalink: /blog/:title
  pages:
    output: true
    permalink: /:title

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6